server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
      path: /swagger-ui-custom.html
      operationsSorter: method

spring:
  datasource:
    url: jdbc:mysql://localhost/emazon-user
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update


appDescription: "Emazon API"
appVersion: "1.0.0"